"""Backward-compatible re-exports — canonical geometry lives in ``frame_geometry`` (SOTA-06)."""

from frame_geometry import (  # noqa: F401
    LetterboxMeta,
    bbox_iou_norm,
    compute_letterbox_meta,
    frame_matches_target_wh,
    letterbox_bgr_to_wh,
    letterbox_image,
    letterbox_roundtrip_iou,
    map_norm_bbox_xyxy_between_frame_shapes,
    pad_boxes,
    prepare_detector_frame,
    prepare_detector_pipeline_frame,
    prepare_yolo_detector_frame,
    resolve_binary_track_imgsz,
    resolve_detector_canvas_wh,
    scale_boxes_norm,
    unmap_letterbox_norm_xyxy_to_source_norm_xyxy,
    unpad_boxes,
    xyxy_pixels_to_norm,
)

__all__ = [
    "LetterboxMeta",
    "bbox_iou_norm",
    "compute_letterbox_meta",
    "frame_matches_target_wh",
    "letterbox_bgr_to_wh",
    "letterbox_image",
    "letterbox_roundtrip_iou",
    "map_norm_bbox_xyxy_between_frame_shapes",
    "pad_boxes",
    "prepare_detector_frame",
    "prepare_detector_pipeline_frame",
    "prepare_yolo_detector_frame",
    "resolve_binary_track_imgsz",
    "resolve_detector_canvas_wh",
    "scale_boxes_norm",
    "unmap_letterbox_norm_xyxy_to_source_norm_xyxy",
    "unpad_boxes",
    "xyxy_pixels_to_norm",
]
