x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "3"

services:
  nginx:
    image: birdlense_nginx:latest
    container_name: birdlense_nginx
    depends_on:
      - web
      - ui
    ports:
      - "${NGINX_HTTP_PORT:-80}:8080"
      - "${NGINX_WS_PORT:-8081}:8081"
    volumes:
      - ./data:/srv/data
      - /var/lib/docker/containers:/docker_logs:ro # Expose logs in nginx
    logging: *default-logging

  processor:
    image: birdlense_processor:latest
    container_name: birdlense_processor
    expose:
      - "8082"
      - "8083"
      - "8084"
      - "8085"
      - "8086"
      - "8087"
      - "8088"
      - "8089"
    volumes:
      - ./app_config:/app/src/app_config
      - ./data:/app/data
    environment:
      - API_URL_BASE=http://web:8000/api/processor
      # Optional: override Go2RTC URL (default from config: http://go2rtc:1984)
      - GO2RTC_URL=${GO2RTC_URL:-}
      - MQTT_BROKER=${MQTT_BROKER:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
    command: python src/main.py
    depends_on:
      - web
    logging: *default-logging

  web:
    image: birdlense_web:latest
    container_name: birdlense_web
    depends_on:
      - ntfy
    volumes:
      - /proc:/host/proc:ro # Access CPU/memory stats
      - /sys:/host/sys:ro # Access temperature sensors
      - ./app_config:/app/app_config
      - ./data:/app/data
    logging: *default-logging

  ui:
    image: birdlense_ui:latest
    container_name: birdlense_ui
    logging: *default-logging

  ntfy:
    container_name: birdlense_ntfy
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      TZ: "America/New_York" # optional: set desired timezone
      NTFY_BEHIND_PROXY: "true"
      NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
      NTFY_BASE_URL: "http://birdlense.local:8081"
    logging: *default-logging
