"""TTL секунд для кэшей ответов /api/ui (общие для разбитых модулей #198)."""

CACHE_STATUS_SEC = 5
CACHE_SPECIES_LIST_SEC = 45
CACHE_SPECIES_OBSERVED_SEC = 45
CACHE_SPECIES_TRACK_REGEN_SEC = 45
CACHE_BIRD_FAMILIES_SEC = 300
CACHE_MIGRATION_SEC = 120
CACHE_TIMELINE_SEC = 20
CACHE_FAVORITES_CATALOG_SEC = 20
CACHE_UNKNOWNS_SEC = 12
CACHE_DETECTION_FRAMES_SEC = 45

UNKNOWNS_LIMIT_MAX = 500
